### PR TITLE
Finishig Ecto in Elixir path

### LINKED ISSUE #25: Ecto Elixir path (Chapter 1 to 3)
## Ecto chapter 1 - Introduction

There are diferent adapter for ecto in Elixir, keeping this in mind for this project the postgresql adapter was used, defining it in the dependencies of a new project:
```elixir
{:ecto_sql, "~> 3.2"}, # Ecto
{:postgrex, "~> 0.15"} # Adapter
```
Database configuration for the Friends application:
```elixir
config :friends, Friends.Repo,
  database: "friends_repo",
  username: "postgres",
  password: "postgres",
  hostname: "localhost"
```
Migration to create the people table:
```elixir
defmodule Friends.Repo.Migrations.CreatePeople do
  use Ecto.Migration

  def change do
    create table(:people) do
      add :name, :string, null: false
      add :age, :integer, default: 0
    end
  end
end
```
And finally the schema to access to that table:
```elixir
defmodule Friends.Person do
  use Ecto.Schema

  schema "people" do
    field :name, :string
    field :age, :integer, default: 0
  end
end
```
## Changesets

We can do changes over a struct schema with the Changeset functions, cast/3 and change/2, like the example below, where we change the name of a Person struct:
```elixir
iex> Ecto.Changeset.cast(%App.Person{name: "Bob"}, %{"name" => "Jack"}, [:name, :age])
%Ecto.Changeset<
  action: nil,
  changes: %{name: "Jack"},
  errors: [],
  data: %Friends.Person<>,
  valid?: true
>
```
### Validations

There are some validations for changesets, in order to guarantee that the information given to the changeset is valid:
```elixir
def test_changeset(struct, params) do
  struct
  # Fields allowed to go through and be modified
  |> cast(params, [:name, :age])
  # ensures age is included in the range 0 to 99 (enumerable)
  |> validate_inclusion(:age, 0..99)
  |> validate_exclusion(:name, ~w(max ben))
  # ensures that the name is always required
  |> validate_required([:name])
  # ensures that the name length is always above 2
  |> validate_length(:name, min: 4)
  |> validate_fictional_name()
end
```

### LINKED ISSUE #27: Ecto Elixir path (Chapter 4 to 5)
## Associations
Created and tested the associations ```Belongs to/Has many```, ```Belongs to/Has one``` and ```Many to Many```.

Then create a new Movie to test the insertion, association, etc:
```elixir
movie = %Movie{title: "Jurassic Park", tagline: "Just dinosaurs"}
```
And then insert it to the database with the Repo module:
```elixir
movie = Repo.insert!(movie)
```
Associating a new character to the movie created above and inserting it to the database:
```elixir
character = Ecto.build_assoc(movie, :characters, %{name: "Alan Grant"})
Repo.insert!(character)
```

## Querying
With the data already in the database we can now query that data with the following functions:

### get and get_by
Using ```Repo.get/3``` for IDs:
```elixir
movie = Repo.get(Movie, 1)
```
Using ```Repo.get_by/3``` for given criterias:
```elixir
movie = Repo.get(Movie, title: "Jurassic Park")
```

### from
We can use ```Ecto.Query.from/2``` macro to create a query and then execute it with ```Repo.all/2``` like so:
```elixir
query = from(Movie, where: [title: "Jurassic Park"], select: [:title, :tagline])
Repo.all(query)
```
The code above will give us the title and tagline of the movies call explicitly `Jurassic Park`.
```elixir
query = from m in Movie,
              join: c in Character,
              on: m.id == c.movie_id,
              where: c.name == "Alant Grant",
              select: {m.title, c.name}
Repo.all(query)
```
The code above will give us just the title of a movie and the name of a character where the movie id is equals in both, and additional  where the name of the character is `Alant Grant`.

### PR DESCRIPTION
**Pull request by CristhianRodriguezMolina**
- Basics
- Changesets
- Executable
- Associations
- Querying

### CODE REVIEW

**Review by luishurtado — CHANGES_REQUESTED** [review]
What is the binary file `ecto/friends/friends`?

**Comment by CristhianRodriguezMolina** [comment]
Its the executable created with escript, should i delete it?

**Comment by CristhianRodriguezMolina** [comment]
I already delete it

**Comment by luishurtado** [comment]
> I already delete it

The deletion was not really necessary. I just wanted to check if you have an understanding of the reason for such a file. No problem, let's move forward.

**Review by luishurtado — APPROVED** [review]

**Comment by CristhianRodriguezMolina** [comment]
Understood, thank you.

**Pull request merged**
